apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  type: NodePort
  selector:
    app: go-web-app
  ports:
  - name: go-web-app-service-port
    port: 8080
    targetPort: 8080
    protocol: TCP
